version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    labels: [dependencies, ci]

  - package-ecosystem: terraform
    directories:
      - /infra/bootstrap
      - /infra/environments/demo
      - /infra/environments/nonprod
      - /infra/environments/production
      - /infra/github-release-role
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    labels: [dependencies, terraform]
